- name: Checks that nginx installed and running properly
  command: systemctl status nginx
  register: command_result
  changed_when: False
  failed_when: "'active (running)' not in command_result.stdout"

- name: Sucsesfull instalation nginx
  debug:
    msg: "nginx installed and running properly: {{command_result.stdout.split('\n')[2]}}"
